# General Settings
baseURL = "https://manhattanpianotuner.com/" #YOUR SITE URL
languageCode = "en-us"
theme = "mytheme"
resourceDir = "../resources"
paginate = 6
summaryLength = 20
DefaultContentLanguage = "en"
title = "Manhattan Piano Tuner | 5 Star Reviews!"
googleAnalytics = "G-TW140BWEHC" # Add your identifier. 

# Menu Settings
[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "#about-section"
  weight = 1
[[menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "#resume-section"
  weight = 2
[[menu.main]]
  identifier = "works"
  name = "Works"
  url = "#works-section"
  weight = 3
[[menu.main]]
  identifier = "pricing"
  name = "Pricing"
  url = "#pricing-section"
  weight = 4
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "#blog-section"
  weight = 5
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "#contact-section"
  weight = 6
[[menu.main]]
  identifier = "pages"
  name = "Pages"
  url = "#pages"
  weight = 7
[[menu.main]]
  identifier = "pages-blog"
  parent = "pages"
  name = "Blog List"
  url = "/blog/"
  weight = 1
[[menu.main]]
  identifier = "pages-works"
  parent = "pages"
  name = "Works List"
  url = "/portfolio/"
  weight = 2

# Main Settings
[params]
defaultSkin = "dark"
dateFormat = "January 2, 2006"
authorName = "Notorious Octopus"
description = "Easily Book a Piano Tuning Online!"
googleAnalytics = "G-TW140BWEHC" # Add your identifier. 
googleTag = "AW-739908831"

# Preloader Settings
[params.preloader]
logo = "images/pianosmall.png"

# Header Settings
[params.header]
logo = "images/pianosmall.png"

# Footer Settings
[params.footer]
copyright = "Â© 2025 Notorious Octopus. All Rights Reserved"
developer = "Notorious"

# Social Settings
[[params.social]]
title = "Google Reviews"
icon = "fab fa-google"
url = "https://www.google.com/maps/place/Manhattan+Piano+Tuner/@40.6884131,-73.9423885,17z/data=!4m8!3m7!1s0x89c25b73af27bbdb:0xced72af027638328!8m2!3d40.6884131!4d-73.9423885!9m1!1b1!16s%2Fg%2F11h6bmzy8d?entry=ttu&g_ep=EgoyMDI1MDUwNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D"
weight = 1


# Portfolio Settings
[params.portfolio]
homeNumOfItems = 12
[[params.portfolio.filters]]
name = "UI UX Design"
slug = "ui-ux-design"
[[params.portfolio.filters]]
name = "Photography"
slug = "photography"
[[params.portfolio.filters]]
name = "Development"
slug = "development"
[[params.portfolio.filters]]
name = "Branding"
slug = "branding"

# Sitemap Settings
[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"
