# General Settings
title = "Manhattan Piano Tuner | Same Day Apointments"
baseURL = "https://www.manhattanpianotuner.com" 
languageCode = "en-us"
theme = "mytheme"
resourceDir = "resources"
paginate = 10
summaryLength = 30 
DefaultContentLanguage = "en"

[backend]
name = "git-gateway"
branch = "main"


# Menu Settings
[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "#about-section"
  weight = 1


[[menu.main]]
  identifier = "pricing"
  name = "Pricing"
  url = "#pricing-section"
  weight = 4
[[menu.main]]
  identifier = "blog"
  name = "Piano FAQ"
  url = "#blog-section"
  weight = 5
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "#contact-section"
  weight = 6


# Main Settings
[params]
defaultSkin = "dark"
dateFormat = "January 2, 2006"
authorName = "BMickman"
googleAnalytics = "G-TW140BWEHC"
  logo = "/images/piano32.png" 
  description = "NYC's Favorite Piano Tuner! Affordable rates & appointments at a time that works for you!"


# Preloader Settings
[params.preloader]
logo = "images/pianosmall.png"

# Header Settings
[params.header]
logo = "images/pianosmall.png"

# Footer Settings
[params.footer]
copyright = "Â© 2024 Manhattan Piano Tuner. All Rights Reserved"
developer = "Notorious Octopus"

# Social Settings

[[params.social]]
title = "Google Maps"
icon = "fab fa-google"
url = "https://maps.app.goo.gl/J83B3nHySXiks6YP7/"
weight = 1
[[params.social]]
title = "Facebook"
icon = "fab fa-facebook"
url = "https://www.facebook.com/manhattanpianotuner/"
weight = 2

# Portfolio Settings
[params.portfolio]
homeNumOfItems = 12
[[params.portfolio.filters]]
name = "UI UX Design"
slug = "ui-ux-design"
[[params.portfolio.filters]]
name = "Photography"
slug = "photography"
[[params.portfolio.filters]]
name = "Development"
slug = "development"
[[params.portfolio.filters]]
name = "Branding"
slug = "branding"

# Sitemap Settings
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
