name = "mytheme"
license = "GPL"
licenselink = ""
description = "Manhattan Piano Tuner"
homepage = "Book a Piano Tuning Today!"
tags = ["clean", "minimal", "blog", "responsive", "personal", "google analytics", "bootstrap", "portfolio", "resume", "modern", "cv", "contact form", "creative"]
features = ['bootstrap 4', 'responsive design', 'blog', 'responsive', 'minimal', 'resume', 'cv', 'hugo-theme', 'portfolio', 'creative', 'contact-form']
min_version = "0.41"

[author]
  name = "Notorious Octopus"
  homepage = "https://notoriousoctopus.com/"
